name: Lint and Test

on:
  push:
    branches: [main]
    paths:
      - '**/*.py'
  pull_request:
    branches: [main]
    paths:
      - '**/*.py'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.7.17
        uses: actions/setup-python@v5
        with:
          python-version: '3.7.17'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest

      - name: Run pylint
        run: |
          pylint phone_matcher tests --fail-under=8.5

      - name: Run tests
        run: |
          pytest tests
