name: Lint and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    runs-on: ubuntu-20.04  # Или ubuntu-18.04, если нужна более старая ОС

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.7.3
        uses: actions/setup-python@v5
        with:
          python-version: '3.7.3'  # Точная версия из manifest
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest

      - name: Run pylint
        run: |
          pylint phone_matcher tests --fail-under=8.5 || echo "Pylint завершился с ошибками" && exit 0

      - name: Run tests
        run: |
          pytest tests -v
